server:
  port: 8091
  servlet:
    context-path: /connet-installer-engine
spring:
  application:
    name: connet-installer-engine
  datasource:
    url: jdbc:postgresql://ec2-3-211-221-185.compute-1.amazonaws.com:5432/dr7if2dj1rl24
    username: ahrnmoojyuugwt
    password: 4c6460faaeaa50b79582c8afe6a8855a1fb5be6423fd810b0c83291f6ff1b397
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    generate-ddl: true
api:
  urlServer: 'http://localhost:8091/connet-installer-engine'
  name: 'API: @project.name@'
  description: '@project.description@'
  version: '@project.version@'
  installer:
    host: 'https://app-challenge-api.herokuapp.com'
    v1:
      basePath: '/installers'
